version: "2.1"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
     - /your/path/nginx-proxy-volume/conf.d:/etc/nginx/conf.d
     - /your/path/nginx-proxy-volume/vhost.d:/etc/nginx/vhost.d
     - /your/path/nginx-proxy-volume/html:/usr/share/nginx/html
     - /your/path/nginx-proxy-volume/certs:/etc/nginx/certs:ro
    labels:
     - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
     - "80:80"
     - "443:443"

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    volumes_from:
     - nginx
    volumes:
     - /your/path/nginx-proxy-volume/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
     - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
     - nginx-gen
    environment:
     - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    volumes_from:
     - nginx
    volumes:
     - /your/path/nginx-proxy-volume/certs:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro

  your-app:
    depends_on:
     - nginx-gen
     - nginx-letsencrypt
    environment:
     - VIRTUAL_HOST=
     - VIRTUAL_PORT=
     - LETSENCRYPT_HOST=
     - LETSENCRYPT_EMAIL=
    container_name: "your-app"
    image: nginx:latest
    ports:
     - "80"
